import {initTheme} from './theme.ts';
import {initNavigation} from './navigation.ts';
import {initSearch} from './search.ts';
import {initRecentPosts} from './feed.ts';
import {initArticle} from './article.ts';
import {initTechnicalContent} from './technical-content.ts';
import {initHighlighting} from './highlighting.ts';
import {initDiagrams} from './diagrams.ts';
initTheme();initNavigation();initSearch();initArticle();initTechnicalContent();initHighlighting();initDiagrams();
void initRecentPosts();
