import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {assets,pug,root} from '../../tools/generate.ts';
const origin='https://blogs.fastcyberdefense.com';const prefix='https://cdn.jsdelivr.net/npm/mermaid@11.17.2/dist/';
async function route(page:import('@playwright/test').Page,view:string,feedOK=true){
 const html=await readFile(`.preview/${view}.html`,'utf8');const requests:string[]=[];
 await page.route(origin+'/**',r=>{requests.push(r.request().url());if(r.request().url().includes('/feeds/'))return feedOK?r.fulfill({contentType:'application/json',body:JSON.stringify({feed:{entry:[{title:{$t:'Cloud publication'},link:[{rel:'alternate',href:origin+'/other'}],category:[{term:'Research'}]}]}})}):r.abort();return r.fulfill({contentType:'text/html',body:html});});return requests;
}
test('catalog navigation, filtering, focus and image dimensions survive all engines',async({page},info)=>{
 const requests=await route(page,'home');await page.goto('/');await expect(page.locator('.post-card')).toHaveCount(4);await page.keyboard.press('/');await expect(page.locator('#search-query')).toBeFocused();await page.locator('#search-query').fill('incident');await expect(page.locator('.post-card:visible')).toHaveCount(1);await page.getByRole('button',{name:'Clear filter'}).click();await expect(page.locator('#search-query')).toBeFocused();await expect(page.locator('.post-card:visible')).toHaveCount(4);
 const hrefs=await page.locator('.post-card h2 a').evaluateAll(xs=>xs.map(x=>x.getAttribute('href')));expect(new Set(hrefs).size).toBe(4);for(const image of await page.locator('.card-image img').all()){await expect(image).toHaveAttribute('width','800');await expect(image).toHaveAttribute('height','450');}
 await page.locator('#theme-toggle').click();const scan=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze();expect(scan.violations).toEqual([]);await info.attach('cross-engine-axe',{body:JSON.stringify(scan),contentType:'application/json'});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:info.outputPath('catalog.png'),fullPage:true});
 await page.locator('#search-query').fill('cloud');await page.locator('#search-query').press('Enter');await expect(page).toHaveURL(/\/search\?q=cloud/);await info.attach('requests',{body:JSON.stringify(requests),contentType:'application/json'});
});
test('article discovery, copy success/failure and print remain usable',async({page},info)=>{
 await route(page,'article');await page.goto('/article');await expect(page.locator('[data-related-list] a')).toHaveCount(1);await expect(page.locator('.related-fallback')).toBeVisible();
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(text:string)=>{document.documentElement.dataset.copy=text;}}}));await page.getByRole('button',{name:'Copy bash code',exact:true}).click();expect(await page.locator('html').getAttribute('data-copy')).toBe(await page.locator('code.language-bash').textContent());
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('denied');}}}));await page.getByRole('button',{name:'Copy bash code',exact:true}).click();await expect(page.locator('#fcd-status')).toContainText('Copy unavailable');
 await page.locator('.article-toc summary').click();await page.locator('.article-toc a').first().click();await expect(page.locator('#article-body h2').first()).toBeFocused();
 const metrics=await page.evaluate(()=>({navigation:performance.getEntriesByType('navigation').map(x=>x.toJSON()),supportedEntryTypes:PerformanceObserver.supportedEntryTypes,scrollWidth:document.documentElement.scrollWidth,viewport:innerWidth}));expect(metrics.scrollWidth).toBeLessThanOrEqual(metrics.viewport+1);await info.attach('synthetic-observations-not-field-vitals',{body:JSON.stringify(metrics),contentType:'application/json'});
 await page.emulateMedia({media:'print'});await expect(page.locator('.site-header')).toBeHidden();await expect(page.locator('.related-articles')).toBeHidden();await expect(page.locator('#article-body')).toBeVisible();await page.screenshot({path:info.outputPath('print.png'),fullPage:true});
});
test('fallback, menu escape and no-JS enlarged text retain native navigation',async({page,browser},info)=>{
 await route(page,'article',false);await page.goto('/article');await expect(page.getByRole('button',{name:'Retry publications'})).toHaveCount(2);await expect(page.locator('.related-fallback')).toBeVisible();
 if((info.project.use.viewport?.width||1280)<640){await page.locator('#menu-toggle').click();await page.locator('#search-query').focus();await page.keyboard.press('Escape');await expect(page.locator('#menu-toggle')).toBeFocused();await expect(page.locator('#primary-navigation')).toBeHidden();}
 const context=await browser.newContext({javaScriptEnabled:false,viewport:info.project.use.viewport,colorScheme:info.project.use.colorScheme});try{const p=await context.newPage();const html=(await readFile('.preview/article.html','utf8')).replace('</head>','<style>html{font-size:200%}p{letter-spacing:.12em;word-spacing:.16em}</style></head>');await p.route(origin+'/**',r=>r.fulfill({contentType:'text/html',body:html}));await p.goto(origin+'/article');await expect(p.locator('.related-fallback')).toBeVisible();await expect(p.locator('form[role="search"]')).toBeVisible();expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}finally{await context.close();}
});
test('actual pinned Mermaid renders and preserves source when blocked',async({page},info)=>{
 const compiled=await assets();const data=JSON.parse(await readFile('fixtures/technical-content.json','utf8'));data.diagrams=data.diagrams.slice(0,1);const html=pug.renderFile(path.join(root,'fixtures/technical-libraries.pug'),{...compiled,data});let bytes=0;
 await page.route(prefix+'**',async r=>{const rel=decodeURIComponent(new URL(r.request().url()).pathname.split('/dist/')[1]||'');const base=path.resolve('node_modules/mermaid/dist');const file=path.resolve(base,rel);if(!file.startsWith(base+path.sep)||!file.endsWith('.mjs'))return r.abort();const body=await readFile(file);bytes+=body.length;return r.fulfill({contentType:'text/javascript',headers:{'access-control-allow-origin':'*'},body});});
 await page.route(origin+'/**',r=>r.fulfill({contentType:'text/html',body:html}));await page.goto('/technical');await expect(page.locator('.fcd-diagram')).toHaveAttribute('data-state','rendered',{timeout:30000});await expect(page.locator('.diagram-output svg')).toHaveCount(1);const source=await page.locator('.diagram-source pre').textContent();await page.locator('#theme-toggle').click();await expect(page.locator('.fcd-diagram')).toHaveAttribute('data-state','rendered',{timeout:30000});expect(await page.locator('.diagram-source pre').textContent()).toBe(source);await info.attach('real-library-bytes',{body:JSON.stringify({bytes}),contentType:'application/json'});
 await page.route(prefix+'**',r=>r.abort());await page.reload();await expect(page.locator('.fcd-diagram')).toHaveAttribute('data-state','error',{timeout:20000});await expect(page.locator('.diagram-source pre')).toBeVisible();expect(await page.locator('.diagram-source pre').textContent()).toBe(source);
});
